# Generated by Django 4.1 on 2023-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Namebasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('nconst', models.TextField(blank=True, null=True)),
                ('primaryname', models.TextField(blank=True, db_column='primaryName', null=True)),
                ('birthyear', models.TextField(blank=True, db_column='birthYear', null=True)),
                ('deathyear', models.TextField(blank=True, db_column='deathYear', null=True)),
                ('primaryprofession', models.TextField(blank=True, db_column='primaryProfession', null=True)),
                ('knownfortitles', models.TextField(blank=True, db_column='knownForTitles', null=True)),
            ],
            options={
                'db_table': 'namebasics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleakas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.TextField(blank=True, db_column='titleId', null=True)),
                ('ordering', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('isoriginaltitle', models.TextField(blank=True, db_column='isOriginalTitle', null=True)),
            ],
            options={
                'db_table': 'titleakas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titlebasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('titletype', models.TextField(blank=True, db_column='titleType', null=True)),
                ('primarytitle', models.TextField(blank=True, db_column='primaryTitle', null=True)),
                ('originaltitle', models.TextField(blank=True, db_column='originalTitle', null=True)),
                ('isadult', models.TextField(blank=True, db_column='isAdult', null=True)),
                ('startyear', models.TextField(blank=True, db_column='startYear', null=True)),
                ('endyear', models.TextField(blank=True, db_column='endYear', null=True)),
                ('runtimeminutes', models.TextField(blank=True, db_column='runtimeMinutes', null=True)),
                ('genres', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titlebasics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titlecrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('directors', models.TextField(blank=True, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titlecrew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleepisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('parenttconst', models.TextField(blank=True, db_column='parentTconst', null=True)),
                ('seasonnumber', models.TextField(blank=True, db_column='seasonNumber', null=True)),
                ('episodenumber', models.TextField(blank=True, db_column='episodeNumber', null=True)),
            ],
            options={
                'db_table': 'titleepisode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleprincipals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.TextField(blank=True, null=True)),
                ('ordering', models.TextField(blank=True, null=True)),
                ('nconst', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titleprincipals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('averagerating', models.FloatField(blank=True, db_column='averageRating', null=True)),
                ('numvotes', models.BigIntegerField(blank=True, db_column='numVotes', null=True)),
            ],
            options={
                'db_table': 'titleratings',
                'managed': False,
            },
        ),
    ]
