# Generated by Django 4.1 on 2023-03-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NameBasics',
            fields=[
                ('nconst', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('primaryname', models.CharField(blank=True, db_column='primaryName', max_length=100, null=True)),
                ('birthyear', models.IntegerField(blank=True, db_column='birthYear', null=True)),
                ('deathyear', models.IntegerField(blank=True, db_column='deathYear', null=True)),
                ('primaryprofession', models.CharField(blank=True, db_column='primaryProfession', max_length=100, null=True)),
                ('knownfortitles', models.CharField(blank=True, db_column='knownForTitles', max_length=255, null=True)),
            ],
            options={
                'db_table': 'namebasics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleAkas',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
                ('attributes', models.CharField(blank=True, max_length=100, null=True)),
                ('isoriginaltitle', models.BooleanField(blank=True, db_column='isOriginalTitle', null=True)),
            ],
            options={
                'db_table': 'titleakas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleBasics',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titletype', models.CharField(blank=True, db_column='titleType', max_length=100, null=True)),
                ('primarytitle', models.CharField(blank=True, db_column='primaryTitle', max_length=100, null=True)),
                ('originaltitle', models.CharField(blank=True, db_column='originalTitle', max_length=100, null=True)),
                ('isadult', models.BooleanField(blank=True, db_column='isAdult', null=True)),
                ('startyear', models.IntegerField(blank=True, db_column='startYear', null=True)),
                ('endyear', models.IntegerField(blank=True, db_column='endYear', null=True)),
                ('runtimeminutes', models.IntegerField(blank=True, db_column='runtimeMinutes', null=True)),
                ('genres', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'titlebasics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleCrew',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('directors', models.CharField(blank=True, max_length=100, null=True)),
                ('writers', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'titlecrew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleEpisode',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seasonnumber', models.IntegerField(blank=True, db_column='seasonNumber', null=True)),
                ('episodenumber', models.IntegerField(blank=True, db_column='episodeNumber', null=True)),
            ],
            options={
                'db_table': 'titleepisode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitlePrincipals',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titleprincipals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleRatings',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('averagerating', models.FloatField(blank=True, db_column='averageRating', null=True)),
                ('numvotes', models.BigIntegerField(blank=True, db_column='numVotes', null=True)),
            ],
            options={
                'db_table': 'titleratings',
                'managed': False,
            },
        ),
    ]
