# Generated by Django 4.1 on 2023-03-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleCrew',
            fields=[
                ('tconst', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('directors', models.CharField(max_length=150)),
                ('writers', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'titlecrew',
            },
        ),
    ]
