# Generated by Django 4.1 on 2023-03-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_titlecrew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlecrew',
            options={'managed': False},
        ),
    ]
