# Generated by Django 4.1 on 2023-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_alter_titlecrew_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namebasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('nconst', models.TextField(blank=True, null=True)),
                ('primaryname', models.TextField(blank=True, db_column='primaryName', null=True)),
                ('birthyear', models.TextField(blank=True, db_column='birthYear', null=True)),
                ('deathyear', models.TextField(blank=True, db_column='deathYear', null=True)),
                ('primaryprofession', models.TextField(blank=True, db_column='primaryProfession', null=True)),
                ('knownfortitles', models.TextField(blank=True, db_column='knownForTitles', null=True)),
            ],
            options={
                'db_table': 'namebasics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleakas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.TextField(blank=True, db_column='titleId', null=True)),
                ('ordering', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('isoriginaltitle', models.TextField(blank=True, db_column='isOriginalTitle', null=True)),
            ],
            options={
                'db_table': 'titleakas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titlebasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('titletype', models.TextField(blank=True, db_column='titleType', null=True)),
                ('primarytitle', models.TextField(blank=True, db_column='primaryTitle', null=True)),
                ('originaltitle', models.TextField(blank=True, db_column='originalTitle', null=True)),
                ('isadult', models.TextField(blank=True, db_column='isAdult', null=True)),
                ('startyear', models.TextField(blank=True, db_column='startYear', null=True)),
                ('endyear', models.TextField(blank=True, db_column='endYear', null=True)),
                ('runtimeminutes', models.TextField(blank=True, db_column='runtimeMinutes', null=True)),
                ('genres', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titlebasics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleepisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('parenttconst', models.TextField(blank=True, db_column='parentTconst', null=True)),
                ('seasonnumber', models.TextField(blank=True, db_column='seasonNumber', null=True)),
                ('episodenumber', models.TextField(blank=True, db_column='episodeNumber', null=True)),
            ],
            options={
                'db_table': 'titleepisode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleprincipals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.TextField(blank=True, null=True)),
                ('ordering', models.TextField(blank=True, null=True)),
                ('nconst', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titleprincipals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titleratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tconst', models.TextField(blank=True, null=True)),
                ('averagerating', models.FloatField(blank=True, db_column='averageRating', null=True)),
                ('numvotes', models.BigIntegerField(blank=True, db_column='numVotes', null=True)),
            ],
            options={
                'db_table': 'titleratings',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
